Adapt sh-shell command from rbenv to phpdock

diff --git a/libexec/phpdock-sh-shell b/libexec/phpdock-sh-shell
--- a/libexec/phpdock-sh-shell
+++ b/libexec/phpdock-sh-shell
@@ -2,11 +2,10 @@
 #
 # Summary: Set or show the shell-specific Ruby version
 #
-# Usage: phpdock shell <version>
-#        phpdock shell -
-#        phpdock shell --unset
+# Usage: phpdock shell <version> [-a|--apache]
+#        phpdock shell --unset [-a|--apache]
 #
-# Sets a shell-specific Ruby version by setting the `PHPDOCK_VERSION'
+# Sets a shell-specific Ruby version by setting the `PHP_CLI_DOCKER_IMAGE'
 # environment variable in your shell. This version overrides local
 # application-specific versions and the global version.
 #
@@ -15,7 +14,7 @@
 # Run `phpdock versions' for a list of available Ruby versions.
 #
 # When `-` is passed instead of the version string, the previously set
-# version will be restored. With `--unset`, the `PHPDOCK_VERSION`
+# version will be restored. With `--unset`, the `PHP_CLI_DOCKER_IMAGE`
 # environment variable gets unset, restoring the environment to the
 # state before the first `phpdock shell` call.
 
@@ -24,33 +23,68 @@ set -e
 
 # Provide phpdock completions
 if [ "$1" = "--complete" ]; then
+  if [ $# -eq 1 ]; then
+    cat $MAIN_PATH/etc/cli_versions
+  else
+    cat $MAIN_PATH/etc/apache_versions
+  fi
   echo --unset
-  echo system
-  exec phpdock-versions --bare
+  echo --apache
+  echo --help
+  exit 0
 fi
+
+# Config getopt
+TEMP=`getopt -o a,u --long apache,unset -n $PROG -- "$@"`
+eval set -- "$TEMP"
+MODE=cli
+
+# Parse arguments
+while true ; do
+  case "$1" in
+    -a|--apache)
+      MODE=apache
+      shift;;
+    --unset)
+      ACTION=unset
+      shift;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+  esac
+done
 
 version="$1"
 shell="$(basename "${PHPDOCK_SHELL:-$SHELL}")"
 
-if [ -z "$version" ]; then
-  if [ -z "$PHPDOCK_VERSION" ]; then
-    echo "phpdock: no shell-specific version configured" >&2
-    exit 1
+function get_version {
+  if [ -z "$1" ]; then
+    echo "phpdock: no shell-specific version configurated for $MODE" >&2
   else
-    echo 'echo "$PHPDOCK_VERSION"'
-    exit
+    if [ "$MODE" = "cli" ]; then
+      echo 'echo "$PHP_CLI_DOCKER_IMAGE"'
+    else
+      echo 'echo "$PHP_SERVER_DOCKER_IMAGE"'
+    fi
+  fi
+}
+
+if [ -z "$version" ]; then
+  if [ "$MODE" = "cli" ]; then
+    get_version PHP_CLI_DOCKER_IMAGE
+  else
+    get_version PHP_SERVER_DOCKER_IMAGE
   fi
 fi
 
-if [ "$version" = "--unset" ]; then
+if [ "$ACTION" = "--unset" ]; then
   case "$shell" in
   fish )
-    echo 'set -gu PHPDOCK_VERSION_OLD "$PHPDOCK_VERSION"'
-    echo "set -e PHPDOCK_VERSION"
+    echo 'set -gu PHP_CLI_DOCKER_IMAGE_OLD "$PHP_CLI_DOCKER_IMAGE"'
+    echo "set -e PHP_CLI_DOCKER_IMAGE"
     ;;
   * )
-    echo 'PHPDOCK_VERSION_OLD="$PHPDOCK_VERSION"'
-    echo "unset PHPDOCK_VERSION"
+    echo 'PHP_CLI_DOCKER_IMAGE_OLD="$PHP_CLI_DOCKER_IMAGE"'
+    echo "unset PHP_CLI_DOCKER_IMAGE"
     ;;
   esac
   exit
@@ -60,36 +94,36 @@ if [ "$version" = "-" ]; then
   case "$shell" in
   fish )
     cat <<EOS
-if set -q PHPDOCK_VERSION_OLD
-  if [ -n "\$PHPDOCK_VERSION_OLD" ]
-    set PHPDOCK_VERSION_OLD_ "\$PHPDOCK_VERSION"
-    set -gx PHPDOCK_VERSION "\$PHPDOCK_VERSION_OLD"
-    set -gu PHPDOCK_VERSION_OLD "\$PHPDOCK_VERSION_OLD_"
-    set -e PHPDOCK_VERSION_OLD_
+if set -q PHP_CLI_DOCKER_IMAGE_OLD
+  if [ -n "\$PHP_CLI_DOCKER_IMAGE_OLD" ]
+    set PHP_CLI_DOCKER_IMAGE_OLD_ "\$PHP_CLI_DOCKER_IMAGE"
+    set -gx PHP_CLI_DOCKER_IMAGE "\$PHP_CLI_DOCKER_IMAGE_OLD"
+    set -gu PHP_CLI_DOCKER_IMAGE_OLD "\$PHP_CLI_DOCKER_IMAGE_OLD_"
+    set -e PHP_CLI_DOCKER_IMAGE_OLD_
   else
-    set -gu PHPDOCK_VERSION_OLD "\$PHPDOCK_VERSION"
-    set -e PHPDOCK_VERSION
+    set -gu PHP_CLI_DOCKER_IMAGE_OLD "\$PHP_CLI_DOCKER_IMAGE"
+    set -e PHP_CLI_DOCKER_IMAGE
   end
 else
-  echo "phpdock: PHPDOCK_VERSION_OLD is not set" >&2
+  echo "phpdock: PHP_CLI_DOCKER_IMAGE_OLD is not set" >&2
   false
 end
 EOS
     ;;
   * )
     cat <<EOS
-if [ -n "\${PHPDOCK_VERSION_OLD+x}" ]; then
-  if [ -n "\$PHPDOCK_VERSION_OLD" ]; then
-    PHPDOCK_VERSION_OLD_="\$PHPDOCK_VERSION"
-    export PHPDOCK_VERSION="\$PHPDOCK_VERSION_OLD"
-    PHPDOCK_VERSION_OLD="\$PHPDOCK_VERSION_OLD_"
-    unset PHPDOCK_VERSION_OLD_
+if [ -n "\${PHP_CLI_DOCKER_IMAGE_OLD+x}" ]; then
+  if [ -n "\$PHP_CLI_DOCKER_IMAGE_OLD" ]; then
+    PHP_CLI_DOCKER_IMAGE_OLD_="\$PHP_CLI_DOCKER_IMAGE"
+    export PHP_CLI_DOCKER_IMAGE="\$PHP_CLI_DOCKER_IMAGE_OLD"
+    PHP_CLI_DOCKER_IMAGE_OLD="\$PHP_CLI_DOCKER_IMAGE_OLD_"
+    unset PHP_CLI_DOCKER_IMAGE_OLD_
   else
-    PHPDOCK_VERSION_OLD="\$PHPDOCK_VERSION"
-    unset PHPDOCK_VERSION
+    PHP_CLI_DOCKER_IMAGE_OLD="\$PHP_CLI_DOCKER_IMAGE"
+    unset PHP_CLI_DOCKER_IMAGE
   fi
 else
-  echo "phpdock: PHPDOCK_VERSION_OLD is not set" >&2
+  echo "phpdock: PHP_CLI_DOCKER_IMAGE_OLD is not set" >&2
   false
 fi
 EOS
@@ -108,15 +142,15 @@ containsElement () {
 # Make sure the specified version is installed.
 VERSIONS=(`phpdock-versions`)
 if containsElement $version ${VERSIONS[@]}  >/dev/null; then
-  if [ "$version" != "$PHPDOCK_VERSION" ]; then
+  if [ "$version" != "$PHP_CLI_DOCKER_IMAGE" ]; then
     case "$shell" in
     fish )
-      echo 'set -gu PHPDOCK_VERSION_OLD "$PHPDOCK_VERSION"'
-      echo "set -gx PHPDOCK_VERSION \"$version\""
+      echo 'set -gu PHP_CLI_DOCKER_IMAGE_OLD "$PHP_CLI_DOCKER_IMAGE"'
+      echo "set -gx PHP_CLI_DOCKER_IMAGE \"$version\""
       ;;
     * )
-      echo 'PHPDOCK_VERSION_OLD="$PHPDOCK_VERSION"'
-      echo "export PHPDOCK_VERSION=\"$version\""
+      echo 'PHP_CLI_DOCKER_IMAGE_OLD="$PHP_CLI_DOCKER_IMAGE"'
+      echo "export PHP_CLI_DOCKER_IMAGE=\"$version\""
       ;;
     esac
   fi
