Check if exist and show message

diff --git a/libexec/phpdock-install b/libexec/phpdock-install
--- a/libexec/phpdock-install
+++ b/libexec/phpdock-install
@@ -160,7 +160,8 @@ case "$OPT" in
   install)
     if [ -z $1 ]; then
       PHP_VERSION=`cat $PHP_VERSION_FILE`
-      VERSIONS=(`list_php_versions $TYPE true | grep $PHP_VERSION`)
+      VERSIONS=(`list_php_versions $TYPE true | grep -w $PHP_VERSION || true`)
+      [ "${#VERSIONS[@]}" -eq 0 ] && ( echo "phpdock: version not found: $PHP_VERSION"; exit 1)
       VERSIONS=(${VERSIONS[@]} "exit")
       createmenu "${VERSIONS[@]}"
     else
