Develop shell command

diff --git a/libexec/phpdock b/libexec/phpdock
--- a/libexec/phpdock
+++ b/libexec/phpdock
@@ -18,6 +18,37 @@ fi
 export PROG=`basename $0`
 export MAIN_PATH=`realpath $0 | xargs dirname | xargs dirname`
 
+if enable -f "${BASH_SOURCE%/*}"/../libexec/rbenv-realpath.dylib realpath 2>/dev/null; then
+  abs_dirname() {
+    local path="$(realpath "$1")"
+    echo "${path%/*}"
+  }
+else
+  [ -z "$PHPDOCK_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
+
+  READLINK=$(type -p greadlink readlink | head -1)
+  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
+
+  resolve_link() {
+    $READLINK "$1"
+  }
+
+  abs_dirname() {
+    local cwd="$PWD"
+    local path="$1"
+
+    while [ -n "$path" ]; do
+      cd "${path%/*}"
+      local name="${path##*/}"
+      path="$(resolve_link "$name" || true)"
+    done
+
+    pwd
+    cd "$cwd"
+  }
+fi
+
+
 shopt -s nullglob
 
 export PATH="$MAIN_PATH/libexec:${PATH}"
