Added apache options

diff --git a/libexec/phpdock-prefix b/libexec/phpdock-prefix
--- a/libexec/phpdock-prefix
+++ b/libexec/phpdock-prefix
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 # Summary: Display prefix for a php docker version
-# Usage: phpdock prefix [<version>]
+# Usage: phpdock prefix [--apache] [<version>]
 #
 # Displays complete image name of a php version. If no
-# version is given, `phpdock prefix' displays the location of the
-# currently selected version.
+# version is given, `phpdock prefix' displays the complete name 
+# of the currently selected version.
 
-set -e
 [ -n "$PHPDOCK_DEBUG" ] && set -x
 
 # Provide phpdock completions
@@ -14,19 +13,37 @@ if [ "$1" = "--complete" ]; then
   if [ "$#" -eq 1 ]; then
     echo system
     echo --help
+    echo --apache
   fi
   exit 0
 fi
 
+# Config getopt
+TEMP=`getopt -o a --long apache -n $PROG -- "$@"`
+eval set -- "$TEMP"
+
+MODE=php
+# Parse arguments
+while true ; do
+  case "$1" in
+    --apache)
+      MODE=apache
+      PARAM=--apache
+      shift;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+  esac
+done
+
 if [ -n "$1" ]; then
   PHP_CLI_DOCKER_IMAGE="$1"
 elif [ -z "$PHP_CLI_DOCKER_IMAGE" ]; then
-  PHP_CLI_DOCKER_IMAGE="$(phpdock-version-name)"
+  PHP_CLI_DOCKER_IMAGE="$(phpdock-version-name $PARAM)"
 fi
 
 if [ "$PHP_CLI_DOCKER_IMAGE" = "system" ]; then
   whereis -b php | awk '{print $2}'
-  exit 0
+  exit 0fi
 fi
 
 containsElement () {
@@ -36,11 +53,10 @@ containsElement () {
   return 1
 }
 
-
-PHPDOCK_PREFIX=(`docker images --format "{{.Repository}}:{{.Tag}}" $PHP_CLI_DOCKER_IMAGE`)
+PHPDOCK_PREFIX=(`docker images --format "{{.Repository}}:{{.Tag}}" | grep $MODE | grep $PHP_CLI_DOCKER_IMAGE`)
 
 if ! containsElement $PHP_CLI_DOCKER_IMAGE ${PHPDOCK_PREFIX[@]} ; then
-  echo "phpdock: version \`${PHP_CLI_DOCKER_IMAGE}' not installed" >&2
+  echo "phpdock: version \`${PHP_CLI_DOCKER_IMAGE}' not installed $MODE" >&2
   exit 1
 fi
 
